import com.acing.eventos.Participante;
import com.esotericsoftware.jsonbeans.Json;
import com.esotericsoftware.jsonbeans.OutputType;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
        // Serializador JSON
        Json json = new Json(OutputType.json);

        // Objeto para serializar inicializado
        Object obj = new Object() {
            int[] numeros;
            String texto;

            Object init() {
                numeros = new int[] { 0, 2, 3 };
                texto = "Mi texto";

                return this;

            }
        }.init();

        // Salida por consola serializada en formato facil de leer
        System.out.println(json.prettyPrint(obj));
        
        
        Participante.mapaParticipantes.put("LEGANES", new Participante("Leganes"));
        Participante.mapaParticipantes.put("ALAVES", new Participante("Alaves"));
        
        //Me encuantro Leganes
        Participante miParticipante = Participante.mapaParticipantes.get("LEGANES");
    }
}
